### PR TITLE
Build docs to HTML

### PR DESCRIPTION
**Pull request by pomegranited**
Uses [mkdocs](http://www.mkdocs.org/) to build the documentation files to HTML.

* moves documentation *.md files to `docs/`
* adds `mkdocs.yml` configuration file
* updates README to describe how to build the docs.
* fixes broken links noticed by mkdocs.

CC @bradenmacdonald

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
@pomegranited Do you need a review? And would @antoviaque need to set this up on opencraft.com?

**Comment by antoviaque** [comment]
@pomegranited Thanks for this! I built it on opencraft.com, which gave http://opencraft.com/doc/openedx-deployment/analytics/aws_setup/ -- btw is there a way to have a root reference URL? Ie get http://opencraft.com/doc/openedx-deployment/ to work, so that we don't have to reference subpages, which might later be renamed/moved?

**Comment by pomegranited** [comment]
@antoviaque Yep!  Done with b167f25.  `mkdocs` is really good at automatically determining the files and links for the table of contents, so I just put in a placeholder index file.

Also found some formatting issues, and got stuck into minor content tweaks with 607cabd.

**Comment by antoviaque** [comment]
@pomegranited Perfect, thanks! I've updated http://opencraft.com/doc/openedx-deployment/ with the latest from this branch, all good on my side. :+1:

**Comment by mtyaka** [comment]
@pomegranited This looks great!

Is it possible to get acronyms in section names in navigation properly capitalized ("Aws setup" -> "AWS setup", "Rds" -> "RDS", "Elastic ip" -> Elastic IP")?
The only other minor issue I noticed is that the three JSON policy documents aren't properly formatted in "Aws setup". I guess it's because there are extra spaces in front of "```" markers.

:+1:

- [x] I looked at the generated docs.
- [x] I read through the code
- [x] Includes documentation (it's all documentation :D)

**Comment by pomegranited** [comment]
Thanks @mtyaka !  mkdocs auto-generates the menu from the file names it discovers, so I've renamed them to use proper uppercase acronyms.

Also fixed the policy JSON, and noticed that mkdocs doesn't like [reference links](https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet#links), so fixed them too.

**Comment by pomegranited** [comment]
@antoviaque  This PR cleaned up a bunch of things, so do you mind to rebuild to  http://opencraft.com/doc/openedx-deployment/?

Thank you!

**Pull request merged**
